# 项目信息配置
project:
  name: tally
  version: 1.0.0
  env: production

# WEB服务器配置
server:
  port: 8080

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://ohuolaila.mysql.rds.aliyuncs.com:3306/tally?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: huolaila
    password: Huolaila@1688
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # JSON返回配置
  jackson:
    # 默认时区
    time-zone: GMT+8
    # 默认日期格式化
    date-format: yyyy-MM-dd HH:mm:ss

# MyBatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Swagger配置
swagger:
  host:
  title: ${project.name}接口文档
  description: ${project.name}接口文档
  enabled: true
  # 禁用swagger时的重定向地址
  redirect-uri: /

# 日志配置
logback:
  level: INFO
  appender: ${project.env}
# dao层的日志设置为debug，方便查看sql
logging:
  level:
    com.tally.dao: debug
# JWT
jwt:
  header: Authorization
  refresh_token_header: RefreshToken
  secret: mySecret
  #token有效期一年
  access_token_expiration: 31536000
  refresh_token_expiration: 31536000
  tokenHead: "Bearer "